name: 每日疫情打卡

on:
  push:
  schedule:
    - cron: '00 18,19 * * *'

jobs:
  attendance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Report
        run: python Auto_Report.py -U ${{ secrets.USERNAME }} -P ${{ secrets.PASSWORD }}
